아래 문제들은 결과 출력까지 실행 후 ipynb  파일과 .py 파일로 제출  
print(b)의 결과가 다음과 같이 되는 code를 작성하시오..  
b는 a를 이용하여 정의 함.   

1.   
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [56]:
import numpy as np
a=np.arange(16)

b=a.reshape(1, 16)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


2.   
[  [ 0  1  2  3  4  5  6  7]  
   [ 8  9 10 11 12 13 14 15]  ]


In [13]:
import numpy as np
a=np.arange(16)
b=a.reshape(2, -1)



print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


3.
 
[ [ [ 0  1]  
    [ 2  3]  
    [ 4  5]  
    [ 6  7]  
    [ 8  9]  
    [10 11]  
    [12 13]  
    [14 15]]  ]  

In [50]:
import numpy as np
a=np.arange(16)
b=a.reshape(1, -1, 2)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


4. 

[ [[ 0]  
   [ 1]  
   [ 2]]  

 [ [ 3]  
   [ 4]  
   [ 5] ]  

 [ [ 6]  
   [ 7]  
   [ 8]  ]  

 [ [ 9]  
   [10]  
   [11] ] ]  


In [68]:
import numpy as np
a=np.arange(12)
b=a.reshape(4, -1, 1)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]


5. [8]  



In [49]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1, 3].reshape(1)
print(b)

[8]
