In [4]:
import numpy as np
x = np.array([[1,2,3], [4, 5, 6]])
y = np.array([[7,8,9], [10, 11, 12]])

# np.concatenate((x, y), axis = 0)
# np.concatenate((x, y), axis = 1)
np.vstack((x, y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
import numpy as np
a = np.arange(10)
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# a.reshape(5, 2)
a.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# a.shape
a1 = a[np.newaxis, :]
# print(a1)
# a1.shape

a2 = a[:, np.newaxis]
# print(a2)
a2.shape


(8, 1)

In [22]:
import numpy as np
ages = np.array([13, 20, 4, 7, 28, 29])
# ages[2:3]
# ages[:4]
# ages[3:]
y = ages >= 20
# print(y)
ages[ages >= 20]

array([20, 28, 29])

In [24]:
import numpy as np
a = np.array([[1,2,3], [4,5,6,], [7,8,9]])
a[1,2]
a[1,2] = 12
print(a)

[[ 1  2  3]
 [ 4  5 12]
 [ 7  8  9]]


In [29]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
# a[1:2, 0:1]
a[1, :]
# a[:, 2]

array([[4]])

In [28]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [34]:
import numpy as np
b = a[0, :]
# print(b)
b[1] = 3
a[0][1]

c = 5 * a
c[1,1]


25

In [39]:
import numpy as np
a =np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
b = a[0,:]
# print(b)
b[1] = 3
# a[0,1]

c = 5 * a
c[1,1]

10